[package]
name = "pylock751"
version = "0.2.0"
edition = "2024"
license = "MIT"
description = "Library for reading and modifying PEP751 pylock.toml files."
repository = "https://github.com/vulncraft/pylock751"
exclude = [".github/*"]

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
toml = "0.9.11"
